name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: P0 and P1 tests
        run: make -f Makefile.p0 test && make -f Makefile.p1 test
